linuxdeepin/linglong-pica

- misc/libexec/linglong/builder/helper/install_dep
在旧版本base中没有/packages.list文件,仍需使用dpkg/status文件
Log:
> fix: The old version of base does not support skip installation

- cli/deb/deb.go
- tools/fs/fs.go
* 直接替换Exec获取到的命令中的路径，不对路径做其他判断，保留原状
* 思维导图MindMaster、 亿图项目管理软件、中望CAD、悟空图像等应用使用自带脚本运行,Exec字段开头为sh，导致获取可执行文件失败，添加判断
Log: fix get bin file error
> fix: fix get bin file error

- misc/libexec/linglong/builder/helper/install_dep
尝试修复deb包中的相对路径的软链接
部分dev包会使用相对路径引用so文件, 这些文件可能存在于base中
Log:
> feat: Attempt to fix broken symlinks in the deb package

- cli/command/adep/adep.go
如果 deps 参数为空会导致，拉取整个仓库
Log: fix empty parameters
> fix: fix empty parameters

- cli/command/convert/convert.go
- cli/deb/deb.go
- cli/linglong/linglong.go
修复 Exec %U %F 等占位符被写入到 start.sh 中，导致桌面环境无法正确替换掉 %U %F等问题，删除 start.sh 作为启动入口，保留原Exec，只替换 $PREFIX，需要通过 ll-cli 安装完应用后，通过双击 desktop 文件的方式能正常启动。
Log: fix Exec
> fix: fix Exec

- cli/appimage/convert/convert.go
Use org.deepin.base/23.1.0 when convert appimage
Log:
> fix: glib version is too low when run app of conversion

- cli/comm/config.go
- cli/linglong/linglong.go
在以20开头的base和runtime版本号与23开头的版本号使用的base和runtime的名称并没保持一致，先在程序中进行判断，重新设置特定的base和runtime
修复 ll-cli install 安装base时使用runtime的版本号问题
Log: reset base and runtime
> chore: reset base and runtime for UOS20

- cli/appimage/convert/convert.go
- cli/command/convert/convert.go
- cli/linglong/linglong.go
Some appimage packages use libraries in packages(LD_LIBRARY_PATH),not need output check(ldd,config),so skip it.
> fix(appimage-convert): failed to convert appimage

- cli/deb/deb.go
需要删除aptly的镜像缓存，否则下次使用相同镜像名，依旧第一次指定的软件包。如一开始aptly镜像为beige指定了vlc软件包，后续添加vlc-bin到beige镜像，发现并不会新增，beige镜像依然只有vlc，故每次更新先删除。
Log: remove aptly cache
> fix: remove aptly cache

- cmd/ll-pica-flatpak/ll-pica-flatpak
修复生成玲珑的版本号错误，如3.0.21生成结果为3..21.0的问题
> fix: fix flatpak version

- misc/libexec/linglong/builder/helper/install_dep
重命名packages.json为packages.list
> fix: wrong file name for package list

- Makefile
- cmd/ll-convert-tool/cli/convert.ab
- cmd/ll-convert-tool/cli/generator.ab
- cmd/ll-convert-tool/core/appimage.ab
- cmd/ll-convert-tool/core/chroot.ab
- cmd/ll-convert-tool/core/deb.ab
- cmd/ll-convert-tool/core/linglong.ab
- cmd/ll-convert-tool/ll-convert-tool
- cmd/ll-convert-tool/main.ab
- cmd/ll-convert-tool/tools/file.ab
- cmd/ll-convert-tool/tools/global.ab
- debian/control
添加 ll-convert-tool 命令用来提供，转换 deb、appimage、flatpak 的功能。
Log: add command
> feat: add ll-convert-tool

- misc/libexec/linglong/builder/helper/install_dep
> feat: disable install share/systemd directory

- misc/libexec/linglong/builder/helper/install_dep
> feat: disable install lib/systemd directory

- cmd/ll-pica-flatpak/ll-pica-flatpak-convert
Convert application ID to lowercase for linglong.yaml generation using tr command. This change ensures compatibility with the linglong package system which requires lowercase package IDs. Both the id and name fields in the template are updated to use the lowercase version of the app ID. Added a newline at the end of the file for proper file formatting.
转置的玲珑应用appid全部使用小写
> fix: ensure lowercase application IDs in linglong.yaml

- cmd/ll-pica-flatpak/ll-pica-flatpak-convert
转制过程中命名执行失败，脚本应该终止，比如ll-builder build
> fix: script doesn't terminate when command fails

- cli/appimage/convert/convert.go
This change improves the AppImage conversion flow by adding default values
when certain fields are not explicitly provided by the user:
- Sets packageName to packageId when packageName is empty
- Sets packageDescription to "converted from appimage" when empty This ensures the conversion process has all required metadata even when minimal input is provided.
> fix: add default values for package name and description

- cli/comm/comm.go
- cli/comm/config.go
- cli/deb/deb.go
- cli/linglong/linglong.go
1. **delMap 改为结构体字段，避免全局变量污染**
- 将原来的全局变量 `delMap` 移入 `Deb` 结构体中，确保在批量处理多个 deb 包时，各包之间互不影响。
- 消除了潜在的状态共享问题，提升了代码的健壮性与可维护性。
2. **完善安装包列表处理逻辑**
- 获取 base/runtime 安装包列表时，改为通过 commit 地址拼接，提高版本定位的准确性。
- 修复 `cat | awk` 执行逻辑中 awk 始终执行的问题，分离判断逻辑避免误判。
- 默认 base/runtime 版本从 `23.0.1` 升级为 `25.2.0`，保持版本一致性。
> fix: improve deb package isolation and base/runtime version handling

- cli/appimage/convert/convert.go
- cli/comm/comm.go
- cli/command/convert/convert.go
- cli/deb/deb.go
1.  Refactored the source directory path in the convert command and deb package build process.
2.  Changed `LlSourceDir` to `LlLocalSourceDir` for local sources to avoid confusion with sources from linglong.yaml.
3.  Adjusted related paths for AppImage extraction, file copying, and script generation to use the new local source directory.
4.  This change improves the clarity and correctness of the source path management, especially during conversion processes where local files are involved.
Influence:
1. Test the appimage conversion process with different AppImage files.
2. Verify that the converted package installs and runs correctly.
3. Ensure that file paths in the generated build scripts are correct.
4. Check the functionality of the deb conversion process with different deb files.
5. …
> refactor: refine source directory path

- cmd/ll-pica/ll-pica.go
- debian/changelog
This commit updates the ll-pica version from 1.2.4-1 to 1.2.5-1. This change is necessary to reflect the latest release of the tool, which may include bug fixes, new features, or other improvements. Updating the version number ensures that users are aware of the version they are using and can easily identify any discrepancies.
Influence:
1. Verify the ll-pica version by running `ll-pica version`.
2. Ensure that the displayed version matches the updated version (1.2.5- 1).
chore: 将 ll-pica 版本提升至 1.2.5-1
此提交将 ll-pica 的版本从 1.2.4-1 更新到 1.2.5-1。 做出此更改是为了反映
该工具的最新版本，其中可能包括错误修复、新功能或其他改进。 更新版本号可
确保用户了解他们正在使用的版本，并且可以轻松识别任何差异。
Influence:
1. 通过运行 `ll-pica version` 验证 ll-pica 版本。
2. 确保显示的版本与更新后的版本（1.2.5-1）匹配。
> chore: bump ll-pica version to 1.2.5-1
