linuxdeepin/linglong-pica

cli/command/convert/convert.go
cli/deb/deb.go

更新生成的 command 命令，添加判断软件包依赖为空的情况
Log: update command and no deps

chore: update command to linglong.yaml and no deps

---

misc/libexec/linglong/builder/helper/install_dep

feat: update runpath of the so file

---

cli/deb/deb.go

* 转换包将原包的版本号信息格式化成玲珑要求的四位版本号，剔除非数字部分
* 删除 TRIPLET 变量设置，玲珑新版本已添加该环境变量
Log: format package version

chore: format package version, remove TRIPLET

---

misc/libexec/linglong/builder/helper/install_dep

runtime 和 develop 的包列表不一致，需要设置即使 dpkg 记录安装过，依然选择安装到应用的依赖库
Log: not skip package

fix: set not skip package

---

cli/command/convert/convert.go
cli/command/init/init.go
cli/config/config.go
cli/config/package_config.go
cli/deb/deb.go

* 设置 base 和 runtime 不同版本
* 对不同 desktop 文件修改
Log: diff version

chore: Different versions of base and runtime

---

cli/command/convert/convert.go

修复 -b 参数构建玲珑应用错误
Log: fix build error

fix: fix build errror

---

debian/changelog

chore: release 1.1.0

---

cli/command/convert/convert.go
cli/deb/deb.go

* 修改代码，兼容非商店应用，至少拥有 desktop 文件
* 修改生成 linglong.yaml 路径不添加架构，一个工作目录只存在一种架构
* 修复打印日志类型错误
Log: compatible conversions

chore: Compatible with non store software conversions

---

cli/command/adep/adep.go
cli/command/convert/convert.go
cli/deb/deb.go
cli/linglong/linglong.go

* 将 install_dep 脚本的内容移动到 linglong.yaml 中
* 优化1位数以上0开头的版本号问题
Log: move install_dep to linglong.yaml

chore: move install_dep to linglong.yaml

---

cli/deb/deb.go

* 修复拷贝 desktop 文件的逻辑
Log: fix movie file

fix: fix move file

---

cli/config/config.go
cli/deb/deb.go

chore: get os arch

---

cli/deb/deb.go

* 对 Exec 开头为 env，可执行文件名，/usr/bin, /opt/apps 的情况进行判断
Log: Modify Exec's judgment

chore: Modify Exec's judgment

---

cmd/ll-pica/ll-pica.go
debian/changelog

chore: release 1.1.1

---

Makefile
debian/linglong-pica.install

代码中没有使用到C相关的内容，纯Go使用，禁用CGO来构建二进制，兼容其他系统使用。
Log: Disable CGO

feat: Disable CGO

---

cli/comm/comm.go
cli/comm/config.go
cli/command/adep/adep.go
cli/command/convert/convert.go
cli/command/init/init.go
cli/config/package_config.go
cli/deb/deb.go
cli/linglong/linglong.go

feat: add --withDep
添加 --withDep 参数，在拉取依赖的时拉取依赖树，会过滤掉 base 和 runtime 中安装过的包
Log: add --withDep

feat: add --withDep

---

cmd/ll-pica/ll-pica.go
debian/changelog

chore: release 1.1.2

---

misc/libexec/linglong/builder/helper/install_dep

隐藏$PREFIX/packages.list 文件不存在时打印的错误信息
Log:

feat: Hide unimportant error messages

---

cli/deb/deb.go

检查 deb 解压后目录，生成对应的脚本
Log: check dir

feat: check dir add script

---

Makefile

添加 install_dep 脚本到deb
Log: add install_dep

chore: add install_dep

---

cmd/ll-pica/ll-pica.go
debian/changelog

* chore: add install_dep
* fix: fix split Exec=
* fix: fix get bin file error
* feat: check dir add script
* fix: The old version of base does not support skip installation
* feat: Hide unimportant error messages
Log: release 1.2.0

chore: release 1.2.0

---

cli/deb/deb.go
cmd/ll-pica/ll-pica.go
debian/changelog

给可能出现错误的命令，添加 || true ，即使错误，继续向后运行
Log: skip build err

fix: skip build err

---

Makefile

修复 install_dep 安装路径错误
Log: fix path error

fix: Fix install_dep path error for install

---

cli/command/convert/convert.go
cli/linglong/linglong.go

为 convert 添加导出文件类型的参数
Log: add exportFile arg

feat: add exportFile arg for convert

---

cli/deb/deb.go

替换 sh 脚本中的原包名为设置的玲珑id
Log: replace sh file

feat: replace sh file

---

cmd/ll-pica/ll-pica.go
debian/changelog

* fix: Fix install_dep path error for install
* feat: add exportFile arg for convert
* feat: replace sh file
Issue: https://github.com/linuxdeepin/developer-center/issues/9556
Log: release 1.2.2

chore: release 1.2.2

---

cli/deb/deb.go
cli/linglong/linglong.go

- 通过发行版获取仓库，减少 aptly 镜像仓库的更新。
- 更新 linglong.yaml 提高可读性

chore: aptly get repo by distro, update linglong.yaml

---

cli/linglong/linglong.go

获取base和runtime列表前尝试安装
Log: install base and runtime

chore: install base and runtime

---

cli/comm/config.go

修改配置文件默认的base和runtime
Log: update config

chore: update default base and runtime

---

Makefile
cli/appimage/convert/convert.go
cli/cobra.go
cmd/ll-appimage-convert/ll-appimage-convert.go

implement appimage convert feature, this feature was moved from linglong builder
Log:

feat: add appimage convert feature

---

Makefile
cmd/ll-pica-flatpak/ll-pica-flatpak
cmd/ll-pica-flatpak/ll-pica-flatpak-convert
cmd/ll-pica-flatpak/ll-pica-flatpak-utils
debian/control

添加 flatpak 转玲珑应用工具
Log: add ll-pica-flatpak

feat: add ll-pica-flatpak

---

cmd/ll-pica-flatpak/ll-pica-flatpak
cmd/ll-pica-flatpak/ll-pica-flatpak-convert

给shell变量添加"" 符号避免参数解析错误
Log: add "" symbol

chore: Add a "" symbol to the variable

---

debian/changelog

release 1.2.3-1
Log: bump version to 1.2.3-1

chore: bump version to 1.2.3-1

---

misc/libexec/linglong/builder/helper/install_dep

缓存deb包的data.tar, 避免反复解压文件, 加快安装速度

feat: use caching to speed up installation

---

debian/changelog

release 1.2.4-1
Log: bump version to 1.2.4-1

chore: bump version to 1.2.4-1

---

misc/libexec/linglong/builder/helper/install_dep

应该先解压到临时文件再移动到缓存, 避免解压过程中断导致缓存损坏

fix: data cache file corruption

---

cli/comm/comm.go
cli/deb/deb.go
cli/linglong/linglong.go

- 修复 adep 添加deb包后生成linglong.yaml 将 git 类型生成 commit 字段错误
- 修复 adep 重新生成 linglong.yaml 会重复 set -x 的问题

fix: fix generate linglong.yaml error

---

cmd/ll-pica-flatpak/ll-pica-flatpak

fix: version conversion error

---

misc/libexec/linglong/builder/helper/install_dep

install_dep 会检查并汇报无法自动修复的无效软链接

feat: install_dep check symbolic link
